language: node_js
node_js:
- '0.10'
- '0.11'
notifications:
  email: false
deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: m3dewsnfjLOSjm3j/occTQb968g4UUUCDIYqKghzwvltqpQ47tUnC2C9cZpInKRIm+M1apBrQh6irCXB3nUqGoc43h4MZy4xUj63N3s/+C2Cv8A1mm7yuAXKJoaECSTSHYgm3K5Wu9WxeyTa2nSDYa7qTH+VUgS1h4kNCDQc8Xg=
  on:
    tags: true
    repo: tjwebb/a.b
    all_branches: true
